### ISSUE TITLE
Focus remains on the command-line when entering/exiting focused mode

### ISSUE THREAD

**Issue by Millani** [junegunn/goyo.vim#188] opened 2019-01-06 09:58 UTC
I am using terminal Vim 8.0 with airline, no tmux and no i3. Whenever I enter or exit focused mode, the cursor goes to and stays at the bottom command-line instead of at the active document. Also, the characters `:wq` get automatically written there at the command-line. I have no customization of Goya besides `set number` in the `goyo_enter` function.

Could anyone help me fix this such that focus gets immediately restored to the active document whenever entering or exiting the focused mode? Thanks!

**Comment by junegunn** [comment] 2019-02-21 10:02
`:wq` is definitely not coming from Goyo. And I can't reproduce the problem your described, maybe because I don't use airline. Since this is not really an issue of Goyo but of your Vim configuration, I'm going to close this.

**Closed by junegunn** 2019-02-21 10:02 UTC
