### ISSUE TITLE
Colorscheme overwriting is not respected in Neovim

### ISSUE THREAD

**Issue by alesandar** [junegunn/goyo.vim#106] opened 2016-03-23 14:05 UTC
I've set some rules to overwrite my default colorscheme.
For example: `hi StatusLine ctermfg=0 ctermbg=3`
While being in distraction-free mode, everything is simply beautiful.
However, when I go back by running `:Goyo!`, my specific rules are not respected.
The statusline has it's default colorscheme background and foreground.

Arch Linux 4.4.5-1
Neovim 0.1.2

**Comment by junegunn** [comment] 2016-03-23 14:14
A duplicate of #103.

**Closed by junegunn** 2016-03-23 14:14 UTC

**Comment by alesandar** [comment] 2016-03-23 15:00
Seems like it's not the first duplicate, excuse me for the incompetence.
Everything works perfect now, thanks!

**Comment by junegunn** [comment] 2016-03-23 15:23
No problem!
