### ISSUE TITLE
Buffer does not resize after opening temporary buffers

### ISSUE THREAD

**Issue by gzagatti** [junegunn/goyo.vim#172] opened 2018-01-31 14:15 UTC
When I open for instance NerdTree in a temporary window, the main window with text does not readjust back to its original position. When closing regular windows I don't have this problem. Do you know what has been disabled by Goyo that causes such behavior?

**Comment by sunbubble** [comment] 2018-07-18 17:00
I have the same problem when the quicklist is closed automatically by vimtex.

**Comment by sunbubble** [comment] 2018-07-19 09:54
If you use the command ":Goyo x" it'll resize to standard dimensions.
For now, as a temporary solution I mapped <leader>G to it.

**Comment by gzagatti** [comment] 2018-07-25 00:46
I can confirm that using @sunbubble tweak works for me as well, so I re-mapped `NERDTreeToggle` when entering `Goyo` to: `  nnoremap <f8> :NERDTreeToggle<cr>:Goyo x<cr>`.

**Comment by habamax** [comment] 2018-11-28 09:09
It also happens when you use `leaderF` plugin to open files/buffers.

BTW, in neovim-qt it doesn't happen

**Comment by oblitum** [comment] 2019-02-03 20:50
This is probably a duplicate of #79, which was closed as wontfix.

**Closed** 2019-02-20 07:58 UTC

**Comment by junegunn** [comment] 2019-02-20 08:01
You can hit `CTRL-W` + `=` to reset the size. And, yeah, `:Goyo x` should do too. That's an interesting approach :)

**Comment by oblitum** [comment] 2019-02-20 08:22
hey you're still alive @junegunn, that's nice :)

....

could you plz take a look at [this](https://github.com/junegunn/vim-plug/issues/814) :P
