### ISSUE TITLE
Goyo doesn't recover italic for base vim configuration

### ISSUE THREAD

**Issue by oblitum** [junegunn/goyo.vim#156] opened 2017-07-03 17:18 UTC
Opening a markdown file with the following content:

```markdown
_italic-text_
```

`:call SyntaxAttr()` (check following plugin list) with the cursor over "italic-text" gives:

- `group: markdownItalic->htmlItalic gui=italic`.

After `:Goyo` it's the same, but after leaving `:Goyo` the highlighting group changes to:

- `group: markdownItalic->htmlItalic`

and the text display ceases to be italic. This was tested with the following minimal `.vimrc`:

```vim
" VIM-PLUG Setup {{{

" Automatic installation {{{
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !mkdir -p ~/.vim/autoload
    silent !curl -fLo ~/.vim/autoload/plug.vim
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    au VimEnter * PlugInstall
endif
" }}}

call plug#begin('~/.vim/plugged')

" Plugins {{{
Plug 'junegunn/goyo.vim'
Plug 'vim-scripts/SyntaxAttr.vim'
" }}}

call plug#end()

" }}}

au! User GoyoLeave
au  User GoyoLeave nested source $MYVIMRC
```

Notice that the solution on https://github.com/junegunn/goyo.vim/issues/44 to reload `.vimrc` on `GoyoLeave` has already been tried without success.

**Comment by ultimatecoder** [comment] 2017-07-14 13:33
@oblitum I am confirming this behavior in my vim editor. I am able to reproduce it.

**Comment by neysofu** [comment] 2017-07-14 17:31
I am having a similar problem. When exiting Goyo, the `highlight` settings in my `.vimrc` don't work anymore. This happend in both vim and neovim.

**Comment by oblitum** [comment] 2017-09-09 21:46
This plugin is nice but the highlighting issue are so many... I've stopped using it but I'd like to suggest to modularize and turn optional anything that's highlighting related. So that one could still get Zen mode window magic without anything highlighting related being touched.

**Comment by junegunn** [comment] 2017-09-10 03:54
Let me close this then.

**Closed by junegunn** 2017-09-10 03:54 UTC

**Comment by oblitum** [comment] 2017-09-10 03:57
@junegunn Sorry if it sounded offensive, was not my intention. Just wanted to leave the suggestion.

**Comment by junegunn** [comment] 2017-09-10 04:03
No offence taken, those issues doesn't bother me and I'm not going to put my time into it.

**Comment by oblitum** [comment] 2017-09-10 04:05
OK, nice. I was thinking of tuning a fork in that sense, if I manage to put this behind a flag I'll offer a pull request.

**Comment by oblitum** [comment] 2017-09-10 22:45
Besides this patch I had in my fork https://github.com/oblitum/goyo.vim/commit/f36555e417d2c6dad6a3d969f320ff5b26d7b7f9, there was a missing piece, I guess this is the remaining part that cause this issue:

> execute 'colo '. get(g:, 'colors_name', 'default')

This is the issue this issue exists.

**Comment by oblitum** [comment] 2017-09-11 00:34
For anyone interested in Goyo's Zen mode but suffer from highlighting issues like this one and others.

With https://github.com/oblitum/goyo.vim/commit/f36555e417d2c6dad6a3d969f320ff5b26d7b7f9 and https://github.com/oblitum/goyo.vim/commit/034479bc30641c09d3bef05cd0b6e84befca1fd9 I've disabled Goyo from touching highlighting.

I then remove the UI artifacts manually from `GoyoEnter`/`GoyoLeave` as per https://github.com/junegunn/goyo.vim/issues/71#issuecomment-250594184:

- [oblitum/dotfiles@aedabd0#.vimrc](https://github.com/oblitum/dotfiles/commit/aedabd0ce2df536bcf77195a397828257a9bc659#diff-4e12c6a37ff2cbb2c93d1b33324a6051)

**Comment by junegunn** [comment] 2017-09-11 04:37
Glad to hear that you found your solution, but that means you can no longer switch color schemes without changing the related code.

Also I can't reproduce the problem with my config. Since reloading color scheme shouldn't cause this issue, I believe the problem lies in your `source $MYVIMRC`, which shouldn't be necessary. If you're concerned about losing custom highlights there are better ways to handle that, i.e. `autocmd ColorScheme`.

**Comment by oblitum** [comment] 2017-09-11 04:41
@junegunn I realize the limitations in that but I prefer this way much more, I check colorscheme quite rarely, and it's lighter as there's no full colorscheme reload.

If you know an alternative solution, I'd be glad to know, I have no idea besides the one I've come with.

**Comment by oblitum** [comment] 2017-09-11 04:44
Also, I do care about the custom highlightings, but for this issue I preferred to focus solely on the problem with native Vim highlighting.

**Comment by oblitum** [comment] 2017-09-11 04:48
Also, it may have not been clear formerly. The issue happens both with and without `source $MYVIMRC`. You have to have a terminal with italics, for this case it's italics specific.

**Comment by junegunn** [comment] 2017-09-11 05:47
> The issue happens both with and without source $MYVIMRC.

I see I was mistaken. But let me clarify what's going on here.

- We don't need Goyo at all to reproduce the issue. Simply switching to any color scheme will cause the problem.
-  But why? Why changing a color scheme affects the highlighting attributes? I would say that this is a bug of Vim itself. Not Goyo.

**Comment by oblitum** [comment] 2017-09-11 12:31
I also think it looks as a Vim issue, but fact is that it's relatively easy to evade: just avoid full reload. I think that Goyo would be quite less problematic if it patched the colorscheme for Zen mode and unpatched with. It would have to store the highlighting for posterior recovery, and if it limited itself to just patch those groups that regard to removing artifacts, which are just a handful, it would be quite rare that any issue would happen with their patch/recovery.

Ultimately this what I'd wish to do in my fork so that I'd not need to do it hardcoded from `GoyoEnter`/`GoyoLeave`, but I've left this for a later time.

**Comment by oblitum** [comment] 2018-11-24 02:30
I've fixed this at https://github.com/oblitum/goyo.vim/commit/f946b24fd7b3a3b151d908a8d3a0d3192e9c2f6f.

I recover colorscheme from a `:redir` backup of color groups Goyo needs to patch, instead of reapplying the user's colorscheme entirely.

**Comment by oblitum** [comment] 2018-11-24 02:30
I can make a pull for it if there's interest.

**Comment by nickwynja** [comment] 2018-11-26 00:39
@oblitum Your fix in https://github.com/oblitum/goyo.vim/commit/372a2d458555f5ae56b5ef9156ced6e28fe07fac seems to work nicely to solve the italics issue. I need to manually run `set foldcolumn=0` and `set signcolumn=no` after entering Goyo-mode to clean up some additional artifacts. It doesn't appear to be working to run these in `goyo_enter()` though.

I see you've adjusted the `grp` here: https://github.com/oblitum/goyo.vim/commit/372a2d458555f5ae56b5ef9156ced6e28fe07fac#diff-76b494d73254bc11a2d717fdee9e5daaR135. Maybe that could effect this? I'll try to dig further on my own tomorrow.

**Comment by oblitum** [comment] 2018-11-26 00:43
@nickwynja yes, I've removed some groups on my own because removing them don't play nice in my setup, I should have do that in a separate commit. You just need to add them back to the list. Or use my master. Besides that fix, I also have an additional commit where I deprecate GoyoEnter for GoyoEnterPre and GoyoEnterPost, for more precise control of autocmd before entering Goyo and after entering it. Original GoyoEnter is like GoyoEnterPost.

**Comment by oblitum** [comment] 2018-11-26 00:50
I will rebase my master and have that part in a separate commit.

**Comment by oblitum** [comment] 2018-11-26 01:04
@nickwynja I've rebased my master and isolated the fix while keeping the original groups at https://github.com/oblitum/goyo.vim/commit/04f5bfcc929ca1f32828f2012560b3c8f33ac887.

(I've also updated the link on the comments above)

**Comment by nickwynja** [comment] 2018-11-26 13:07
@oblitum Thanks! This is working better. There is a minor issue I'm running into with restoring highlights links:

```
Error detected while processing function goyo#execute[20]..<SNR>143_goyo_off[59]..<SNR>143_restore:
line   10:
E413: Too many arguments: ":highlight link SignColumn ctermfg=12 ctermbg=242 guifg=Cyan guibg=Grey LineNr"
```
But replacing [this substitute](https://github.com/oblitum/goyo.vim/blob/04f5bfcc929ca1f32828f2012560b3c8f33ac887/autoload/goyo.vim#L125) with the following seems to work for me:

```vim
execute 'hi link ' . substitute(cmd, '\(\w\+\)\s.*links\s\+to\s*', '\1 ', '')
```

**Comment by oblitum** [comment] 2018-11-26 13:35
@nickwynja hmm, that fix is not good, you're not recovering highlight links correctly. If you care, please open an issue in my fork referring to the colorscheme you're using. As this regex worked for all my colorschemes, which are not many, I thought it would work for all forms of output Vim/NeoVim gives when calling `hi group`, to recover it later from that output, but the output may differ depending even on your window size, I try to cover that but dunno what your case is bringing of new.

**Comment by oblitum** [comment] 2018-11-26 13:54
Hmm, correction, your `substitute` may in fact be fine and fixing the issue, but I'd still like to check the issue myself.

**Comment by pappasam** [comment] 2019-06-10 19:26
@oblitum This fixes the issue for me:

```viml
function! s:goyo_leave()
  syntax off
  syntax on
endfunction

autocmd! User GoyoLeave nested call <SID>goyo_leave()
```

I'm honestly not sure why this works over other options, but you can thank this post for the solution: https://stackoverflow.com/a/8674739

**Comment by oblitum** [comment] 2019-06-10 19:41
@pappasam thx, that's good to know! Though I still prefer my solution because I avoid fully reloading colorschemes and syntax, which means it's less intrusive and avoids blinking.
